Builder: build cache
googlefonts/gftools pull request #355
Opened 2021-03-31 11:29 UTC by m4rc1e

If a user hasn't updated their source files or they haven't tampered with the binary output dirs, there's no reason why we need to recompile the fonts using fontmake when they run the builder. In order to implement this, I've made a very simple checksum file cache which uses sqlite3 (no external dependencies etc).

So far there are two reasons why a user may rerun the builder when they haven't touched the sources:
1. modifying a VF STAT table
2. Instantiating static fonts

The performance gains are excellent. For Maven Pro, cached builds go from 40 secs to 6 secs. This will definitely make STAT and instantiating less frustrating.

Still wip. Need to hook it up to static font generation.

Implements https://github.com/googlefonts/gftools/issues/353

2021-03-31 12:50 UTC, graphicore commented
There are other factors that require rebuilding, because they change the result: changed/updated build software/environment and changed configuration. I.e. it could be that a new version of fontTools via fontMake fixes a bug in the resulting binary.

2021-03-31 14:54 UTC, m4rc1e commented
Good point. I will implement those cases as well.

2021-04-09 10:34 UTC, m4rc1e commented
I think we're ready for a first review since all edge cases are now handled.

2021-04-26 09:34 UTC, moyogo requested changes

2021-04-26 09:38 UTC, m4rc1e commented on Lib/gftools/builder/cache.py
> +            source_files.append(f)
Thanks and good catch.

2021-05-19 08:56 UTC, m4rc1e commented
I've stopped working on this since our rust prototype is faster than caching.

2021-05-19 08:56 UTC, closed without merging